<a href="https://colab.research.google.com/github/vishwakarma9470/FeatureEngineering_machine_learning/blob/main/DataEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Encoding

### Nomial/One_Hot_Encoding          (OHE)

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder


In [ ]:
df = pd.DataFrame({
    'color':['red','blue','green','red','blue','green']
                                                                                        ## create a sample dataframe with a categorical variable
})

In [ ]:
df

color
0    red
1   blue
2  green
3    red
4   blue
5  green

In [ ]:
### create an instance of one hot encoder
encoder=OneHotEncoder()

In [ ]:
encoder.fit_transform(df[['color']])

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [ ]:
### fit the encoder to the dataframe and transform the categorical variable
encoder.fit_transform(df[['color']]).toarray()


array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
import pandas as pd
encodded_df=pd.DataFrame(encoder.toarray(),columns=encoder.get_feature_names_out())

AttributeError: 'OneHotEncoder' object has no attribute 'toarray'

In [ ]:
encodded_df

NameError: name 'encodded_df' is not defined

In [ ]:
encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red'], dtype=object)

In [ ]:
pd.concat([df,encodded_df],axis=1)

In [ ]:
# Internal assignment

### Label And Ordinal Encoding

In [ ]:
import pandas as pd
from sklearn.preprocessing   import LabelEncoder

In [ ]:
df = pd.DataFrame({
    'color':['red','blue','green','red','blue','green']
                                                                                        ## create a sample dataframe with a categorical variable
})

In [ ]:
df

color
0    red
1   blue
2  green
3    red
4   blue
5  green

In [ ]:
## create an instance of labelencoder
encoder = LabelEncoder()

In [ ]:
encoder.fit_transform(df[['color']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0, 1])

## Ordinal encoding

In [ ]:
## Orcinal encoding
import pandas as pd
from sklearn.preprocessing   import OrdinalEncoder

df = pd.DataFrame({
    'size':['large','small','medium','large','medium','small']
                                                                                        ## create a sample dataframe with a categorical variable
})

In [ ]:
df

size
0   large
1   small
2  medium
3   large
4  medium
5   small

In [ ]:
## create an instance of the orcinalEncoder class and fit_transform
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [ ]:
encoder.fit_transform(df[['size']])

array([[2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.]])

In [ ]:
## Orcinal encoding
import pandas as pd
from sklearn.preprocessing   import OrdinalEncoder

In [ ]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
pd.DataFrame